.PHONY: all libcos

all: libcos

libcos:
	@echo "Building libcos..."
	$(MAKE) -C cos

format:
	@echo "Formatting libcos..."
	$(MAKE) -C cos format

clean:
	@echo "Cleaning libcos..."
	$(MAKE) -C cos clean