#pragma once

constexpr unsigned char kb_action_escape = 0x80;
constexpr unsigned char kb_action_lctl = 0x81;
constexpr unsigned char kb_action_lshift = 0x82;
constexpr unsigned char kb_action_rshift = 0x83;
constexpr unsigned char kb_action_lalt = 0x84;
constexpr unsigned char kb_action_caps = 0x85;
constexpr unsigned char kb_action_f1 = 0x86;
constexpr unsigned char kb_action_f2 = 0x87;
constexpr unsigned char kb_action_f3 = 0x88;
constexpr unsigned char kb_action_f4 = 0x89;
constexpr unsigned char kb_action_f5 = 0x8A;
constexpr unsigned char kb_action_f6 = 0x8B;
constexpr unsigned char kb_action_f7 = 0x8C;
constexpr unsigned char kb_action_f8 = 0x8D;
constexpr unsigned char kb_action_f9 = 0x8E;
constexpr unsigned char kb_action_f10 = 0x8F;
constexpr unsigned char kb_action_numlk = 0x90;
constexpr unsigned char kb_action_scrllk = 0x91;
constexpr unsigned char kb_action_f11 = 0x92;
constexpr unsigned char kb_action_f12 = 0x93;
constexpr unsigned char kb_action_rctl = 0x94;
constexpr unsigned char kb_action_ralt = 0x95;
constexpr unsigned char kb_action_home = 0x96;
constexpr unsigned char kb_action_cup = 0x97;
constexpr unsigned char kb_action_pgup = 0x98;
constexpr unsigned char kb_action_cleft = 0x99;
constexpr unsigned char kb_action_cright = 0x9A;
constexpr unsigned char kb_action_end = 0x9B;
constexpr unsigned char kb_action_cdown = 0x9C;
constexpr unsigned char kb_action_pgdn = 0x9D;
constexpr unsigned char kb_action_insert = 0x9E;
constexpr unsigned char kb_action_delete = 0x9F;
constexpr unsigned char kb_action_ext = 0xE0;

constexpr unsigned char kb_ps2_sc1_released_offset = 0x80;

constexpr unsigned char keypress_to_char_or_action[256] = {0,
														   kb_action_escape,
														   '1',
														   '2',
														   '3',
														   '4',
														   '5',
														   '6',
														   '7',
														   '8',
														   '9',
														   '0',
														   '-',
														   '=',
														   '\b',
														   '\t',
														   'q',
														   'w',
														   'e',
														   'r',
														   't',
														   'y',
														   'u',
														   'i',
														   'o',
														   'p',
														   '[',
														   ']',
														   '\n',
														   kb_action_lctl,
														   'a',
														   's',
														   'd',
														   'f',
														   'g',
														   'h',
														   'j',
														   'k',
														   'l',
														   ';',
														   '\'',
														   '`',
														   kb_action_lshift,
														   '\\',
														   'z',
														   'x',
														   'c',
														   'v',
														   'b',
														   'n',
														   'm',
														   ',',
														   '.',
														   '/',
														   kb_action_rshift,
														   '*',
														   kb_action_lalt,
														   ' ',
														   kb_action_caps,
														   kb_action_f1,
														   kb_action_f2,
														   kb_action_f3,
														   kb_action_f4,
														   kb_action_f5,
														   kb_action_f6,
														   kb_action_f7,
														   kb_action_f8,
														   kb_action_f9,
														   kb_action_f10,
														   kb_action_numlk,
														   kb_action_scrllk,
														   '7',
														   '8',
														   '9',
														   '-',
														   '4',
														   '5',
														   '6',
														   '+',
														   '1',
														   '2',
														   '3',
														   '0',
														   '.',
														   0,
														   0,
														   0,
														   kb_action_f11,
														   kb_action_f12,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   kb_action_escape,
														   '!',
														   '@',
														   '#',
														   '$',
														   '%',
														   '^',
														   '&',
														   '*',
														   '(',
														   ')',
														   '_',
														   '+',
														   '\b',
														   '\t',
														   'Q',
														   'W',
														   'E',
														   'R',
														   'T',
														   'Y',
														   'U',
														   'I',
														   'O',
														   'P',
														   '{',
														   '}',
														   '\n',
														   kb_action_lctl,
														   'A',
														   'S',
														   'D',
														   'F',
														   'G',
														   'H',
														   'J',
														   'K',
														   'L',
														   ':',
														   '\"',
														   '~',
														   kb_action_lshift,
														   '|',
														   'Z',
														   'X',
														   'C',
														   'V',
														   'B',
														   'N',
														   'M',
														   '<',
														   '>',
														   '?',
														   kb_action_rshift,
														   '*',
														   kb_action_lalt,
														   ' ',
														   kb_action_caps,
														   kb_action_f1,
														   kb_action_f2,
														   kb_action_f3,
														   kb_action_f4,
														   kb_action_f5,
														   kb_action_f6,
														   kb_action_f7,
														   kb_action_f8,
														   kb_action_f9,
														   kb_action_f10,
														   kb_action_numlk,
														   kb_action_scrllk,
														   '7',
														   '8',
														   '9',
														   '-',
														   '4',
														   '5',
														   '6',
														   '+',
														   '1',
														   '2',
														   '3',
														   '0',
														   '.',
														   0,
														   0,
														   0,
														   kb_action_f11,
														   kb_action_f12,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   kb_action_ext,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0};

constexpr unsigned char ext_keypress_to_action[128] = {[0x1C] = '\n',
													   [0x1D] = kb_action_rctl,
													   [0x35] = '/',
													   [0x38] = kb_action_ralt,
													   [0x47] = kb_action_home,
													   [0x48] = kb_action_cup,
													   [0x49] = kb_action_pgup,
													   [0x4B] = kb_action_cleft,
													   [0x4D] = kb_action_cright,
													   [0x4F] = kb_action_end,
													   [0x50] = kb_action_cdown,
													   [0x51] = kb_action_pgdn,
													   [0x52] = kb_action_insert,
													   [0x53] = kb_action_delete};

typedef struct {
	bool lctl, rctl, lshift, rshift, lalt, ralt, caps, numlk, scrllk, ext;
} statemachine_t;

int kp_isaction (unsigned char kp);
int kp_ischar (unsigned char kp);
int kp_isext (unsigned char kp);
int kp_islk (unsigned char kp);

unsigned char map_keypress (statemachine_t* sm, unsigned char kp);
