#pragma once

constexpr unsigned char kb_action_escape = 0x80;
constexpr unsigned char kb_action_lctl = 0x81;
constexpr unsigned char kb_action_lshift = 0x82;
constexpr unsigned char kb_action_rshift = 0x83;
constexpr unsigned char kb_action_lalt = 0x84;
constexpr unsigned char kb_action_caps = 0x85;
constexpr unsigned char kb_action_f1 = 0x86;
constexpr unsigned char kb_action_f2 = 0x87;
constexpr unsigned char kb_action_f3 = 0x88;
constexpr unsigned char kb_action_f4 = 0x89;
constexpr unsigned char kb_action_f5 = 0x8A;
constexpr unsigned char kb_action_f6 = 0x8B;
constexpr unsigned char kb_action_f7 = 0x8C;
constexpr unsigned char kb_action_f8 = 0x8D;
constexpr unsigned char kb_action_f9 = 0x8E;
constexpr unsigned char kb_action_f10 = 0x8F;
constexpr unsigned char kb_action_numlk = 0x90;
constexpr unsigned char kb_action_scrllk = 0x91;
constexpr unsigned char kb_action_f11 = 0x92;
constexpr unsigned char kb_action_f12 = 0x93;

constexpr unsigned char kb_ps2_sc1_released_offset = 0x80;

constexpr unsigned char keypress_to_char_or_action[256] = {0,
														   kb_action_escape,
														   '1',
														   '2',
														   '3',
														   '4',
														   '5',
														   '6',
														   '7',
														   '8',
														   '9',
														   '0',
														   '-',
														   '=',
														   '\b',
														   '\t',
														   'q',
														   'w',
														   'e',
														   'r',
														   't',
														   'y',
														   'u',
														   'i',
														   'o',
														   'p',
														   '[',
														   ']',
														   '\n',
														   kb_action_lctl,
														   'a',
														   's',
														   'd',
														   'f',
														   'g',
														   'h',
														   'j',
														   'k',
														   'l',
														   ';',
														   '\'',
														   '`',
														   kb_action_lshift,
														   '\\',
														   'z',
														   'x',
														   'c',
														   'v',
														   'b',
														   'n',
														   'm',
														   ',',
														   '.',
														   '/',
														   kb_action_rshift,
														   '*',
														   kb_action_lalt,
														   ' ',
														   kb_action_caps,
														   kb_action_f1,
														   kb_action_f2,
														   kb_action_f3,
														   kb_action_f4,
														   kb_action_f5,
														   kb_action_f6,
														   kb_action_f7,
														   kb_action_f8,
														   kb_action_f9,
														   kb_action_f10,
														   kb_action_numlk,
														   kb_action_scrllk,
														   '7',
														   '8',
														   '9',
														   '-',
														   '4',
														   '5',
														   '6',
														   '+',
														   '1',
														   '2',
														   '3',
														   '0',
														   '.',
														   0,
														   0,
														   0,
														   kb_action_f11,
														   kb_action_f12,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   kb_action_escape,
														   '!',
														   '@',
														   '#',
														   '$',
														   '%',
														   '^',
														   '&',
														   '*',
														   '(',
														   ')',
														   '_',
														   '+',
														   '\b',
														   '\t',
														   'Q',
														   'W',
														   'E',
														   'R',
														   'T',
														   'Y',
														   'U',
														   'I',
														   'O',
														   'P',
														   '{',
														   '}',
														   '\n',
														   kb_action_lctl,
														   'A',
														   'S',
														   'D',
														   'F',
														   'G',
														   'H',
														   'J',
														   'K',
														   'L',
														   ':',
														   '\"',
														   '~',
														   kb_action_lshift,
														   '|',
														   'Z',
														   'X',
														   'C',
														   'V',
														   'B',
														   'N',
														   'M',
														   '<',
														   '>',
														   '?',
														   kb_action_rshift,
														   '*',
														   kb_action_lalt,
														   ' ',
														   kb_action_caps,
														   kb_action_f1,
														   kb_action_f2,
														   kb_action_f3,
														   kb_action_f4,
														   kb_action_f5,
														   kb_action_f6,
														   kb_action_f7,
														   kb_action_f8,
														   kb_action_f9,
														   kb_action_f10,
														   kb_action_numlk,
														   kb_action_scrllk,
														   '7',
														   '8',
														   '9',
														   '-',
														   '4',
														   '5',
														   '6',
														   '+',
														   '1',
														   '2',
														   '3',
														   '0',
														   '.',
														   0,
														   0,
														   0,
														   kb_action_f11,
														   kb_action_f12,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0,
														   0};
