.PHONY: all hello

all: hello

bin: hello

hello:
	@echo "Building hello..."
	$(MAKE) -C hello

format:
	@echo "Formatting hello..."
	$(MAKE) -C hello format

clean:
	@echo "Cleaning hello..."
	$(MAKE) -C hello clean