.PHONY: all hello pishell

all: hello pishell

bin: hello pishell

hello:
	@echo "Building hello..."
	$(MAKE) -C hello

pishell:
	@echo "Building pishell..."
	$(MAKE) -C pishell

format:
	@echo "Formatting hello..."
	$(MAKE) -C hello format

clean:
	@echo "Cleaning hello..."
	$(MAKE) -C hello clean